### PR TITLE
Software Status

### PR DESCRIPTION
**Pull request by bobturneruk**
Adds a page that shows an overview of the status of all of the software in the remit FAIRDataPipeline. Very roughly put together - maybe possible to draw status information from individual repositories in future via GitHub API, if desirable. But for now I intend to fill this in to identify gaps and help make the substantial amount of existing information more findable.

### CODE REVIEW

**Review by B0SKAMP — COMMENTED** [review]
It duplicates stuff from software checklist. Could this
replace the individual repo's software checklists, OR 
this CSV get generated from software checklists, OR 
software checklists generated from this CSV?

**Comment by bobturneruk** [comment]
Thanks for the feedback @B0SKAMP - I agree, but I need to have this all in one place, and this seemed like the best place. We should certainly work on consolidating things. Not all the stuff in the software checklist is needed for a high level summary. I'd favour either generating this csv from the checklists, as you say, or doing something more fancy with the github API and dynamically generating the table.

**Comment by RyanJField** [comment]
Perhaps this should be named "Development Status" or "Repository Status" or similar, I agree "Software Status" is too close to the software checklist. It would be good to have links included to the checklists / repo's etc, and use this page as high level overview of the repositories we have.

**Comment by bobturneruk** [comment]
Good point. I've done some renaming and put an explicit comment on the site to address @B0SKAMP's comment up front so we don't end up drifting towards duplication.

**Review by B0SKAMP — APPROVED** [review]
looks good.

**Comment by bobturneruk** [comment]
Thanks @B0SKAMP !

**Pull request merged**
