### PR TITLE
Added FAIR-CLI repository information

### PR DESCRIPTION
**Pull request by kzscisoft**
Added additional development page for FAIR-CLI, this page is instructions for developers on how to use the existing repository as opposed to laying out any final standards. Feedback is welcome, but should be made in either PRs or issues to the FAIR-CLI repository.

### CODE REVIEW

**Comment by soniamitchell** [comment]
* Weightings need edited for this section
* The table of contents is unnecessary, given the submenu on the website
* The title in the nav bar menu could be a little more descriptive or at least consistent with existing items, perhaps FAIR CLI outline? Or could we merge the two CLI pages together?

**Review by soniamitchell — CHANGES_REQUESTED** [review]
* Weightings need edited for this section to avoid potential nav bar menu breakages in the future
* The table of contents is unnecessary, given the submenu on the website
* The title in the nav bar menu could be a little more descriptive or at least consistent, perhaps FAIR CLI functionality and FAIR CLI outline? Or could we merge the two CLI pages together?

**Comment by richardreeve** [comment]
@soniamitchell These changes look pretty simple... if so, do you think you could make them and then merge it? Once we've done that I think we can plan a more significant restructure to merge the two pages together as a second PR.

**Review by soniamitchell — APPROVED** [review]

**Comment by soniamitchell** [comment]
done

**Pull request merged**
