### PR TITLE
Use cases

### PR DESCRIPTION
**Pull request by bobturneruk**
Adds uses cases from MS Teams word document. Hopefully I've not messed the Hugo up too much!

### CODE REVIEW

**Comment by soniamitchell** [comment]
Just wondering if it would be cleaner to have them all on the same page? Since each page has a table of contents on the right hand side of the page, it's easier to browse through use case names there, rather than having to return to the main Use Cases links page.

**Comment by bobturneruk** [comment]
Thanks @soniamitchell - the ToC thing hadn't occurred to me. I'll maybe try it on another branch and we can go with what is preferred.

**Comment by bobturneruk** [comment]
I think your suggestion is clearly better @soniamitchell so I've implemented it in this branch. I suggest this can be merged if you approve.

**Comment by soniamitchell** [comment]
Go for it 👍 I'll have a fiddle around with weightings / the nav bar later on.

**Review by soniamitchell — APPROVED** [review]

**Pull request merged**
