### PR TITLE
Additions to the data registry documentation

### PR DESCRIPTION
**Pull request by agbeltran**

### CODE REVIEW

**Comment by antony-wilson** [comment]
@agbeltran looks good. Is it worth adding something about adding the example data?

**Comment by agbeltran** [comment]
yes, @antony-wilson that would be great - I'm still working on adding something about installing from branches - when I am done, I will get it ready for review and you can add something the sample data? Cheers

**Comment by agbeltran** [comment]
I still need to push the documentation for the registry, and I've only got a placeholder for now, but this covers documentation on running the repo from a branch and the provenance report information cc @richardreeve

**Review by richardreeve — APPROVED** [review]
Shall we merge this now and just make a second PR to replace the placeholder. This is clearly useful as is and an improvement on what we currently have?

**Comment by agbeltran** [comment]
yes, let's do that

**Pull request merged**
