### PR TITLE
Update front page

### PR DESCRIPTION
**Pull request by richardreeve**
@soniamitchell - I've move the intro page to the front page, and the front page to an SCRC sub-page. Does this look okay to you?

### CODE REVIEW

**Comment by soniamitchell** [comment]
The front page is blank for me, I think you need to put *_index.md* (Introduction) in *content/*, not *docs/*.

**Comment by richardreeve** [comment]
How can you see that? I was just guessing where to put things...

**Comment by soniamitchell** [comment]
After that you need to change the weighting on the nav bar headers because they're rearranging themselves when you click on them.

**Comment by soniamitchell** [comment]
I was just going by what I had before.

**Comment by richardreeve** [comment]
I don't know how you're seeing anything though - the website doesn't resolve until you merge it surely?

**Comment by richardreeve** [comment]
Anyway, that's done now?

**Comment by soniamitchell** [comment]
oh.. if you try `hugo server` it makes a local version on http://localhost:1313/

see the readme on this GitHub repo for details ;)

**Comment by richardreeve** [comment]
I've changed a link too now I've moved it up a level.

**Comment by soniamitchell** [comment]
looks good to me 👍

**Review by soniamitchell — APPROVED** [review]

**Pull request merged**
